# Copyright (c) 2024 Ninad Mathpati <ninad.mathpati@securityboat.net>

# Copyright CONTENT

# Project information
site_name: SecurityBoat Workbook
site_url: https://securityboat.github.io/
site_author: Himanshu Gupta
site_description: >-
  SecurityBoat Workbook is an open-source repository of knowledge cultivated through years of penetration testing and expertise contributed by security professionals at SecurityBoat. <br><br>Covering comprehensive security topics, including application, api, network, cloud, and hardware security, this workbook provides valuable insights and practical knowledge to build up your understanding and skills.

# Repository
repo_name: Securityboat/securityboat.github.io
repo_url: https://github.com/Securityboat/securityboat.github.io/
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright @ 2024 SecurityBoat Cybersecurity Solution Private Limited

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  logo: assets/sb_short_logo.png
  favicon: assets/sb_short_logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
    # logo: assets/sb_full_logo.png

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocs-pdf
  # - exclude:
  #     glob:
        # - exclude/this/path/*
        # - "blog/*"
        # - "SUMMARY.md"
  #       # - "*.tmp"
  #       # - "*.pdf"
  #       # - "*.gz"
  #     # regex:
  #     #   - '.*\.(tmp|bin|tar)$'

# Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Securityboat/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/securityboat/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/securityboat/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Securityb0at
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@securityboat

# Extensions
markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: securityboat
      repo: securityboat.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Home: index.md
    - Pentesting:
        - Pentesting/index.md
        - Web Application:
            - Pentesting/Web Application/2fa-bypass.md
            - Pentesting/Web Application/cross-site-scripting.md
            - Pentesting/Web Application/password-reset-functionality.md
            - Pentesting/Web Application/sensitive-information-disclosure.md
            - Pentesting/Web Application/web-cache-poisoning.md
            - Pentesting/Web Application/Directory bruteforcing-fingerprinting.md
            - Pentesting/Web Application/clickjacking.md
            - Pentesting/Web Application/command-injection.md
            - Pentesting/Web Application/cms.md
            - Pentesting/Web Application/crlf-injection-0d-0a.md
            - Pentesting/Web Application/cross-site-request-forgery-csrf.md
            - Pentesting/Web Application/directory-enumeration.md
            - Pentesting/Web Application/encoding.md
            - Pentesting/Web Application/file-inclusion.md
            - Pentesting/Web Application/file-upload-bypass.md
            - Pentesting/Web Application/http-cheat-sheet.md
            - Pentesting/Web Application/http-request-smuggling.md
            - Pentesting/Web Application/insecure-http-methods.md
            - Pentesting/Web Application/idor.md
            - Pentesting/Web Application/insecure-deserialization.md
            - Pentesting/Web Application/jwt-and-its-bypass.md
            - Pentesting/Web Application/oauth.md
            - Pentesting/Web Application/payloads.md
            - Pentesting/Web Application/postmessage-vuls.md
            - Pentesting/Web Application/race-conditions.md
            - Pentesting/Web Application/redirects.md
            - Pentesting/Web Application/response-manipulation.md
            - Pentesting/Web Application/saml-sso.md
            - Pentesting/Web Application/server-side-template-injection-ssti.md
            - Pentesting/Web Application/sql-injection.md
            - Pentesting/Web Application/ssrf.md
            - Pentesting/Web Application/subdomain-enumeration.md
            - Pentesting/Web Application/unristricted-file-upload.md
            - Pentesting/Web Application/web-app-pentest-checklist.md
            - Pentesting/Web Application/web-cache-deception.md
            - Pentesting/Web Application/xxe.md
            - Keyhacks:
              - Pentesting/Web Application/keyhacks/firebase-exploits.md
              - Pentesting/Web Application/keyhacks/gmaps-api-scanner.md
              - Pentesting/Web Application/keyhacks/map-box-api-scanner.md
        - API:
            - Pentesting/API/api-endpoints.md
            - Pentesting/API/graphql.md
            - Pentesting/API/rest.md
            - Pentesting/API/soap.md
        - Android:
            - Pentesting/Android/mobile-infrastructure-and-architecture.md
            - Pentesting/Android/understand-android-os.md
            - Pentesting/Android/understanding-androidmanifest.xml.md
            - Pentesting/Android/deep-dive-into-activities.md
            - Pentesting/Android/content-providers.md
            - Pentesting/Android/intent-and-intent-filters.md
            - Pentesting/Android/rooting-and-connecting-devices.md
            - Pentesting/Android/broken-cryptography.md
            - Pentesting/Android/poor-authorization-and-authenticationntitled.md
            - Pentesting/Android/improper-error-handling.md
            - Pentesting/Android/improper-input-validation.md
            - Pentesting/Android/improper-session-handling.md
            - Pentesting/Android/insecure-data-storage.md
            - Pentesting/Android/unsafe-data-transmission.md
            - Pentesting/Android/unintended-data-leakage.md
            - Pentesting/Android/ssl-pinning.md
            - Pentesting/Android/extraneous-functionality.md
            - Pentesting/Android/reverse-engineer.md
            - Pentesting/Android/command-line-for-android-pt-cheatsheet.md
        - IOS:
            - Pentesting/IOS/untitled.md
            - Pentesting/IOS/how-to-extract-ipa-from-idevice-manually..md
            - Pentesting/IOS/lets-jailbreak-iphone-ipad.md
            - Pentesting/IOS/reverse-engineering.md
            - Pentesting/IOS/setting-up-frida+objection.md
            - Pentesting/IOS/ssl-pinning.md
            - Pentesting/IOS/command-line-cheatsheet-for-ios-pt.md
        - Network:
            - Pentesting/Network/active-info-gathering.md
            - Pentesting/Network/brute-force.md
            - Pentesting/Network/buffer-overflow.md
            - Pentesting/Network/cheatsheet-short.md
            - Pentesting/Network/common-ports-and-services.md
            - Pentesting/Network/dns-zone-transfer-attack.md
            - Pentesting/Network/main-tools.md
            - Pentesting/Network/misc.md
            - Pentesting/Network/oscp-one-page-repository.md
            - Pentesting/Network/oscp-vulnhub-practice-learning.md
            - Pentesting/Network/pivoting.md
            - Pentesting/Network/port-and-services-scanning.md
            - Pentesting/Network/post-exploitation.md
            - Pentesting/Network/priv-escalation.md
            - Pentesting/Network/shells.md
            - Pentesting/Network/smb-enumeration.md
            - Pentesting/Network/snmp-enumeration.md
            - Pentesting/Network/transferring-files.md
        - Thick Client:
            - Linux Application Pentesting:
              - Pentesting/Thick Client/linux-application-pentesting/basics.md
              - Pentesting/Thick Client/linux-application-pentesting/buffer-overflow.md
              - Pentesting/Thick Client/linux-application-pentesting/reversing-linux-applications.md
            - Windows Application Pentesting:
              - Pentesting/Thick Client/windows-application-pentesting/architecture.md
              - Pentesting/Thick Client/windows-application-pentesting/assembly-analysis.md
              - Pentesting/Thick Client/windows-application-pentesting/buffer-overflow.md
              - Pentesting/Thick Client/windows-application-pentesting/dll-hijacking.md
              - Pentesting/Thick Client/windows-application-pentesting/gui-attacks.md
              - Pentesting/Thick Client/windows-application-pentesting/hardcoded-sensitive-information.md
              - Pentesting/Thick Client/windows-application-pentesting/information-gathering.md
              - Pentesting/Thick Client/windows-application-pentesting/lack-of-code-obfuscation.md
              - Pentesting/Thick Client/windows-application-pentesting/memory-analysis.md
              - Pentesting/Thick Client/windows-application-pentesting/registry-monitoring.md
              - Pentesting/Thick Client/windows-application-pentesting/sql-injection.md
              - Pentesting/Thick Client/windows-application-pentesting/testing-approach.md
              - Pentesting/Thick Client/windows-application-pentesting/unquoted-service-paths.md
        - Cloud:
            - Pentesting/Cloud/Best practice rules for Google Cloud Platform.md
            - Pentesting/Cloud/GCP API.md
            - Pentesting/Cloud/GCP Domain Name System (DNS).md
            - Pentesting/Cloud/GCP Identity and Access Management (IAM).md
            - Pentesting/Cloud/GOOGLE VPC.md
            - Pentesting/Cloud/gcp-api.md
        - Secure Code Review:
            - Pentesting/Secure Code Review/appendix-a-glossary.md
            - Pentesting/Secure Code Review/code-review-checklist.md
            - Pentesting/Secure Code Review/manual-code-review.md
            - Pentesting/Secure Code Review/recommendation-and-references.md
            - Pentesting/Secure Code Review/remedial-code-snippets.md
            - Manual Code Crawling:
                - Pentesting/Secure Code Review/manual-code-crawling/searching-for-code-in-.net.md
                - Pentesting/Secure Code Review/manual-code-crawling/searching-for-code-in-classic-asp.md
                - Pentesting/Secure Code Review/manual-code-crawling/searching-for-code-in-java.md
                - Pentesting/Secure Code Review/manual-code-crawling/searching-for-code-in-javascript-and-ajax.md
        - Physical:
            - NodeMCU ESP8266:
                - Pentesting/Physical/NodeMCU ESP8266/Wi-Fi Deauther.md
            - Raspberry Pi:
                - Pentesting/Physical/Raspberry Pi/honeypot-using-raspberry-pi-and-opencanary..md
                - Pentesting/Physical/Raspberry Pi/portable-hacking-machine.md
                - Pentesting/Physical/Raspberry Pi/usb-rubber-ducky-using-raspberry-pi-pico.md
        - Pentesting/Resources.md
    - Bug Bounty:
        - Bug Bounty/README.md
        - Bug Bounty/how-to-get-started-in-a-bug-bounty.md
        - Bug Bounty/bug-bounty-checklist-for-web-app.md
        - Bug Bounty/bug-bounty-checklist-for-android.md
        - Bug Bounty/bug-bounty-dorks.md
        - Bug Bounty/reconnotes.md
        - Bug Bounty/vps.md
        - Bug Bounty Report Templates:
            - Bug Bounty/Report Templates/clickjacking.md
            - Bug Bounty/Report Templates/command-injection.md
            - Bug Bounty/Report Templates/crlf-injection.md
            - Bug Bounty/Report Templates/csrf-cross-site-request-forgery.md
            - Bug Bounty/Report Templates/directory-traversal.md
            - Bug Bounty/Report Templates/dom-xss-document-object-model-based-cross-site-scripting.md
            - Bug Bounty/Report Templates/github-recon.md
            - Bug Bounty/Report Templates/host-header-injection.md
            - Bug Bounty/Report Templates/html-injection.md
            - Bug Bounty/Report Templates/idor-insecure-direct-object-references.md
            - Bug Bounty/Report Templates/insecure-deserialization.md
            - Bug Bounty/Report Templates/ldap-injection.md
            - Bug Bounty/Report Templates/lfi-local-file-inclusion.md
            - Bug Bounty/Report Templates/open-redirect.md
            - Bug Bounty/Report Templates/race-condition.md
            - Bug Bounty/Report Templates/response-manipulation.md
            - Bug Bounty/Report Templates/rfi-remote-file-inclusion.md
            - Bug Bounty/Report Templates/rxss-reflected-cross-site-scripting.md
            - Bug Bounty/Report Templates/sql-injection.md
            - Bug Bounty/Report Templates/ssi-injection.md
            - Bug Bounty/Report Templates/ssrf-server-side-request-forgery.md
            - Bug Bounty/Report Templates/subdomain-takeover.md
            - Bug Bounty/Report Templates/sxss-stored-cross-site-scripting.md
            - Bug Bounty/Report Templates/template-injection.md
            - Bug Bounty/Report Templates/unrestricted-file-upload.md
            - Bug Bounty/Report Templates/use-of-default-credentials.md
    - Tools and Extensions:
        - Tools and Extensions/index.md
        - Tools Cheatsheet for Pentesting:
            - Tools and Extensions/Tools Cheatsheet for Pentesting/metasploit.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/nikto.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/nmap.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/shodan.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/sqlmap.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/wpscan.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/frida.md
            - Tools and Extensions/Tools Cheatsheet for Pentesting/mobile-security-framework-mobsf.md
        - Burp Suite Extensions:
            - Tools and Extensions/Burp Suite Extensions/authmatrix.md
            - Tools and Extensions/Burp Suite Extensions/flow.md
            - Tools and Extensions/Burp Suite Extensions/http-request-smuggler.md
            - Tools and Extensions/Burp Suite Extensions/java-deserialize-scanner.md
            - Tools and Extensions/Burp Suite Extensions/json-js-beautifier.md
            - Tools and Extensions/Burp Suite Extensions/json-web-tokens-jwt4b.md
            - Tools and Extensions/Burp Suite Extensions/saml-raider.md
            - Tools and Extensions/Burp Suite Extensions/wsdler-for-soap-services.md
    - Handbooks:
      - handbook/README.md
      - handbook/CVE-2024-3094-Handbook.md
      - handbook/IDOR-Handbook.md
      - handbook/Insecure-Deserialization-Handbook.md
      - handbook/JWT-Handbook.md
      - handbook/SSTI-Handbook.md
      - handbook/Unrestricted-File-Upload-Handbook.md
    - Other:
        - Other/index.md
        - Command Line Interface:
            - Other/basic-linux-commands/linux-commands.md
            - Other/basic-linux-commands/bash-scripting.md
            - Other/basic-linux-commands/windows.md
        - Mindmaps:
            - Other/Mindmaps/README.md
        - Other/CTF Resources.md
        - Security Comics:
            - Other/Technical Comics/The Story of XSS.md
    - Contribution:
      - Contribution/index.md
      - Contribution/Contributions.md
      - Contribution/rights_and_responsibilities.md
